In [8]:
import pandas as pd
import numpy as np
import warnings; warnings.filterwarnings('ignore')
import json

f = open('List_csv1.txt', 'r', encoding='UTF8')
lines = f.read()
print(lines[1:30])
f.close()




[  0 522 369 125 176 207 242 


In [11]:
data = np.load('test.npy')
print(data)
data[1]

[[  0 522 369 ... 389 390 668]
 [  1 334 153 ... 598 597 479]
 [  2  74 385 ... 815 812 674]
 ...
 [825 956 760 ... 419 420   0]
 [289 785 957 ... 676 671   0]
 [958 193 319 ... 518 517 414]]


array([  1, 334, 153, 295, 889, 244, 649, 580, 828, 119,  72, 188, 839,
       818,  63,   5, 930, 321, 900,  28, 644, 222, 568, 827, 292, 351,
       327, 857,  33, 325, 352, 816, 239, 238, 323, 225, 880, 120, 678,
       157,   7, 107, 719, 426, 218, 179, 111, 662, 685, 201,  82, 156,
       385, 366, 395, 800,  13, 810, 316, 741,  61, 154,  97, 297,  71,
       173, 138, 205, 132, 290, 626, 737, 122, 276, 215, 599, 211, 264,
       811, 684, 460,  34, 371,  40, 368, 473, 431,  35,   3,   8, 925,
       204, 441, 376, 661, 794, 655,  90, 651, 623,  20, 458, 234, 916,
       466, 648, 389, 256,  16, 415, 155, 733, 151, 730, 172, 144, 141,
       716, 174, 706, 943, 126, 771, 700, 184, 123, 185, 390, 824, 524,
       330, 512, 341, 278, 286, 570,  43, 294,  47, 270, 557, 887,  62,
       518,  60, 875, 275, 287, 346, 259, 876,   2,  91, 731, 452, 177,
       591, 425, 710,  69, 546, 550, 866, 181,  89, 536,  66, 759, 399,
       891, 401,  65, 146, 147, 516, 314, 251, 829, 941,  36,  8

In [13]:
import pandas as pd
import numpy as np
import warnings; warnings.filterwarnings('ignore')
import json

movies_df = pd.read_csv("result.csv")
genre_sim_sorted_ind = np.load('result.npy')
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    title_movie = df[df['pk'] == title_name]
    title_index = title_movie.index.values

    similar_indexes = sorted_ind[title_index, : (top_n * 2)]
    similar_indexes = similar_indexes.reshape(-1)

    similar_indexes = similar_indexes[similar_indexes != title_index]

    return df.iloc[similar_indexes].sort_values('weighted_vote', ascending=False)[:top_n]

similar_movies = find_sim_movie(movies_df, genre_sim_sorted_ind, 526896, 5)
similar_movies[['pk']]

pk
522     603
369  831405
125  399566
176  588228
207  848278